# Base docker compose, added to by docker-compose.override or docker-compose.prd. See Readme.md

version: '2'
services:

  web:
    # Build php & apache container see Dockerflile
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfiwa:/var/lib/phpfiwa
      - emon-phpfina:/var/lib/phpfina
      - emon-phptimeseries:/var/lib/phptimeseries
    links:
      # Link to MYSQL DB (see below)
      - db

  db:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      - "MYSQL_HOST=localhost"
    volumes:
      - emon-db-data:/var/lib/mysql/data

volumes:
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-db-data:
    driver: local
  emon-phptimeseries:
    driver: local